# Generated by Django 6.0.2 on 2026-02-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('discord_guild_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('riot_subject', models.CharField(db_index=True, max_length=128)),
                ('riot_game_name', models.CharField(blank=True, default='', max_length=64)),
                ('riot_tag_line', models.CharField(blank=True, default='', max_length=16)),
                ('region', models.CharField(default='ap', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('discord_user_id', models.BigIntegerField(db_index=True)),
                ('discord_guild_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token_enc', models.TextField()),
                ('scope', models.TextField(blank=True, default='')),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='api.accountlink')),
            ],
        ),
    ]
