# Generated by Django 6.0.2 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorantMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_path", models.CharField(max_length=255, unique=True)),
                ("asset_name", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("display_name", models.CharField(max_length=128)),
                ("is_rank_map_pool", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
